# Generated by Django 4.1.2 on 2022-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0002_alter_vendor_email_alter_vendor_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='confirm_password',
        ),
    ]
