# Generated by Django 4.1.2 on 2022-10-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0003_vendortoken_remove_vendor_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
