# Generated by Django 4.1.2 on 2022-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0004_remove_vendor_password_alter_vendor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
