# Generated by Django 4.1.2 on 2022-10-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0009_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
