# Generated by Django 4.1.2 on 2022-10-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0011_screen_showdate_showtime_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seet_no', models.CharField(max_length=3, null=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.screen')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.show')),
            ],
        ),
    ]
