# Generated by Django 4.1.2 on 2022-10-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0015_remove_movie_name'),
        ('vendor_api', '0012_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_api.category'),
        ),
    ]
