# Generated by Django 4.1.2 on 2022-10-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0013_show_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='screen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_api.screen'),
        ),
    ]
