# Generated by Django 4.1.2 on 2022-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0014_alter_show_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked_status',
            field=models.BooleanField(default=False),
        ),
    ]
