# Generated by Django 4.1.2 on 2022-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0016_seat_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
