# Generated by Django 4.1.2 on 2022-10-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0017_show_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_api.screen'),
        ),
    ]
