# Generated by Django 4.1.2 on 2022-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0018_alter_show_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_name',
            field=models.CharField(max_length=20),
        ),
    ]
