# Generated by Django 4.1.2 on 2022-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0019_alter_screen_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
