# Generated by Django 4.1.2 on 2022-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0020_alter_showtime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
