# Generated by Django 4.1.2 on 2022-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_alter_city_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityenquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityenqueryname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
