# Generated by Django 4.1.2 on 2022-10-20 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_cityenquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityenquery',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_api.district'),
        ),
    ]
