# Generated by Django 4.1.2 on 2022-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dateofadd',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('MALAYALAM', 'Malayalam'), ('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=10),
        ),
    ]
