# Generated by Django 4.1.2 on 2022-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityenquery',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
