# Generated by Django 4.1.2 on 2022-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0013_rename_language_movie_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
