# Generated by Django 4.1.2 on 2022-10-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enable_authenticator',
        ),
    ]
