# Generated by Django 4.1.2 on 2022-10-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_remove_user_enable_authenticator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_superusre',
            new_name='is_superuser',
        ),
    ]
