# Generated by Django 4.1.2 on 2022-11-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0020_alter_showtime_time'),
        ('user_api', '0006_user_city_user_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BokkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.screen')),
                ('seet_no', models.ManyToManyField(to='vendor_api.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.show')),
            ],
        ),
    ]
