# Generated by Django 4.1.2 on 2022-11-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_bokkingticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bokkingticket',
            name='ticket_no',
        ),
    ]
