# Generated by Django 4.1.2 on 2022-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_rename_seet_no_bokkingticket_seat_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bokkingticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
