# Generated by Django 4.1.2 on 2022-11-04 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0021_screen_price'),
        ('user_api', '0012_bokkingticket_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.screen')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_api.show')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.bokkingticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
