# Generated by Django 4.1.2 on 2022-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0013_brokercharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercharge',
            name='ticket',
            field=models.IntegerField(),
        ),
    ]
