# Generated by Django 4.1.2 on 2022-11-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_alter_brokercharge_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercharge',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.bokkingticket'),
        ),
    ]
