# Generated by Django 4.1.2 on 2022-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0015_brokercharge_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercharge',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
