# Generated by Django 4.1.2 on 2022-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0016_alter_brokercharge_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brokercharge',
            old_name='price',
            new_name='brokerfee',
        ),
        migrations.AddField(
            model_name='bokkingticket',
            name='brokerfee',
            field=models.FloatField(default=0),
        ),
    ]
