# Generated by Django 4.1.2 on 2022-11-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0017_rename_price_brokercharge_brokerfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercharge',
            name='brokerfee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.bokkingticket'),
        ),
    ]
