# Generated by Django 4.1.2 on 2022-11-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0019_alter_brokercharge_brokerfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercharge',
            name='ticket',
            field=models.IntegerField(unique=True),
        ),
    ]
