# Generated by Django 4.1.2 on 2022-11-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0021_brokercharge_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bokkingticket',
            name='payment_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
